### ISSUE TITLE
image not booting on rpi3

### ISSUE THREAD

**Issue by cprinze** [ezraholm50/BerryCloud#5]
written the image to sdcard as stated, but rpi3 is not booting.
red led=steady
green start flashing slow, getting faster. keeps repeating this

**Comment by ezraholm50** [comment]
Please mount the .img on your desktop/laptop and go to the PI_BOOT partition and remove the content of config.txt. Then copy this in to the file:
`# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
gpu_mem=16`

Do the same for cmdline.txt:
`
dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait`

Then please report back what that did.

**Comment by cprinze** [comment]
it shows a rainbow square. but nothing more

**Comment by ezraholm50** [comment]
Ok hang tight I'll post a link to some other files that all need to be
replaced we can also try boot delay. You'll hear from me in an hour.

Op vr 1 apr. 2016 17:10 schreef cprinze <notifications@github.com>:

> it shows a rainbow square. but nothing more
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/5#issuecomment-204432939>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by cprinze** [comment]
i tried boot_delay=1 and boot_delay=32 without success

**Comment by ezraholm50** [comment]
Ok first try these setups in config.txt, remove everything else and paste this in.
Start with the first and if it works, try another one till it doesnt.

```
gpu_mem=16
boot_delay=2
initial_turbo=60
arm_freq=1200
gpu_freq=250
core_freq=250
sdram_freq=400
over_voltage=0
over_voltage_sdram=0

```

```
gpu_mem=16
boot_delay=2
initial_turbo=60
arm_freq=1250
gpu_freq=250
core_freq=350
sdram_freq=450
over_voltage=2
over_voltage_sdram=2

```

```
gpu_mem=16
boot_delay=2
initial_turbo=60
arm_freq=1300
gpu_freq=250
core_freq=500
sdram_freq=500
over_voltage=6
over_voltage_sdram=6

```

Then make sure your `cmdline.txt `looks like this:
```
smsc95xx.turbo_mode=N dwc_otg.fiq_fix_enable=1 root=/dev/mmcblk0p2 wc_otg.lpm_enable=0  rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait rootdelay bootdelay
```

If that doesn't work, replace the whole PI_BOOT partition with the content of this zip folder:
https://owncloud.rehrstieg102.de/owncloud/index.php/s/ZGt5A6RzjH6SAkG

I look forward hearing from you.

**Comment by ezraholm50** [comment]
Ignore everything above. I found the solution, will post this in the wiki asap!
Please test and report back!

**Comment by ezraholm50** [comment]
Please use the new image, I have uploaded a new one. Also in the download folder is a zip file called PI_BOOT_RPI3.zip please remove the files of the freshly made PI_BOOT partition of the BerryCloud SDCARD and unzip the content of the zip file in there. You should be able to boot.

**Comment by cprinze** [comment]
it works like a charm now :)
great work.

**Comment by ezraholm50** [comment]
Good to hear that, please post any upcoming issues here aswell. We'll work on it to polish the project.

Thanks

**Comment by enoch85** [comment]
:100:
